### ISSUE TITLE
 troubleshoot why it takes a minute to start the daemon set 

### ISSUE THREAD

**Issue by andreaskaris** [openshift/ingress-node-firewall#100]
It takes a minute to start the daemon set pod. Fix this

**Comment by msherif1234** [comment]
most of the time spent in pulling the image because of the image size `433MB`
```
  Normal  Pulling    72s   kubelet            Pulling image "quay.io/mmahmoud/ingress-node-firewall-daemon:latest"
  Normal  Pulled     3s    kubelet            Successfully pulled image "quay.io/mmahmoud/ingress-node-firewall-daemon:latest" in 1m9.338246567s
  Normal  Created    3s    kubelet            Created container daemon
  Normal  Started    3s    kubelet            Started container daemon
```

because the base image used in kind dockerfile `quay.io/centos/centos:stream8` since sriov used the same to build daemonset we probably can continue with that and maybe explore going to alpine as it will reduce the image significantly but has its own limitations
