### ISSUE TITLE
Support for setting rules to specific routes/namespaces?

### ISSUE THREAD

**Issue by sedadas** [openshift/ingress-node-firewall#426]
Hello!

Is there something planned for implementing firewall rules to specific routes/namespaces?

We have the following use case: we have an application that is running on OCP and that we want to expose to our DMZ.
We want to do this using a route and without relying on any reverse proxy. Our OCP cluster is currently firewalled from our DMZ
and if we remove the firewall rule, it would mean that everything in the DMZ would then have access to all exposed services in OCP, which is not ideal.

Our plan is then to implement something of this sort:
* have a global hardened config inside OpenShift that blocks all requests from the DMZ
* only allow access to specific namespaces/routes if required

Would this be possible? If not, how can this be implemented otherwise?

All the best!

**Comment by msherif1234** [comment]
Hi @sedadas thanks for opening this issue, from what u described I wonder if you looked at using [netpol](https://docs.openshift.com/container-platform/4.13/networking/network_policy/about-network-policy.html) for this use case ?

**Comment by msherif1234** [comment]
I believe this where ANP "Admin Network Policy" will try to achieve which is coming in OCP 4.14 release cc'd @tssurya pls confirm

**Comment by msherif1234** [comment]
I will close this issue because its outside node firewall scope

**Comment by msherif1234** [comment]
Close #426

**Comment by tssurya** [comment]
> I believe this where ANP "Admin Network Policy" will try to achieve which is coming in OCP 4.14 release cc'd @tssurya pls confirm

yeah ANP will/should do this.
Currently the version coming out in GA will allow you to block egress from pods to DMZ, if you want to block ingress from outside (DMZ) to the pods inside the cluster, then please comment your use case: https://github.com/kubernetes-sigs/network-policy-api/pull/128/files#r1317640306 because ironically we are actually looking for real use cases where we want to support policy rules for southbound traffic, so far nobody approached us since mostly pods are never accessible directly.

**Comment by tssurya** [comment]
checkout https://network-policy-api.sigs.k8s.io/, https://www.redhat.com/en/blog/using-adminnetworkpolicy-api-to-secure-openshift-cluster-networking for understanding more about ANP
